name: Selenium Tests on iOS

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 15 * * *'

jobs:
  build-ios:
    runs-on: macos-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install .NET 6.0 SDK (optional)
        run: |
          curl -SL https://dot.net/v1/dotnet-install.sh | bash /dev/stdin --channel 6.0
          export PATH=$PATH:$HOME/.dotnet
          dotnet --list-sdks

      - name: Set Xcode Version
        uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '14.3'
          select: true

      - name: Install CocoaPods (if needed)
        run: |
          sudo gem install cocoapods
          pod install --repo-update  # Ensure dependencies are installed

      - name: Build iOS project
        run: |
          xcodebuild \
          -workspace YourApp.xcworkspace \
          -scheme YourAppScheme \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0' \
          clean build

      - name: Run tests on iOS simulator
        run: |
          xcodebuild test \
          -workspace YourApp.xcworkspace \
          -scheme YourAppScheme \
          -sdk iphonesimulator \
          -destination 'platform=iOS Simulator,name=iPhone 14,OS=17.0'
