name: Selenium Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Replace with the version you are using

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test in Chrome
        run: dotnet test --configuration Release --filter "TestCategory=Chrome" --no-build --verbosity normal

      - name: Test in Edge
        run: dotnet test --configuration Release --filter "TestCategory=Edge" --no-build --verbosity normal

      - name: Test in Firefox
        run: dotnet test --configuration Release --filter "TestCategory=Firefox" --no-build --verbosity normal

      - name: Test in Brave
        run: dotnet test --configuration Release --filter "TestCategory=Brave" --no-build --verbosity normal

      - name: Test in Opera
        run: dotnet test --configuration Release --filter "TestCategory=Opera" --no-build --verbosity normal
