name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '0 0 * * *'  # Runs at 12:35 UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install .NET SDK 6.0
        run: |
          wget -O dotnet.tar.gz https://download.visualstudio.microsoft.com/download/pr/20283373-1d83-4879-8278-0afb7fd4035e/56f204f174743b29a656499ad0fc93c3/dotnet-sdk-6.0.100-rc.2.21505.57-linux-x64.tar.gz
          mkdir -p $HOME/dotnet
          tar zxf dotnet.tar.gz -C $HOME/dotnet
          export DOTNET_ROOT=$HOME/dotnet
          export PATH=$PATH:$HOME/dotnet

      - name: Verify .NET SDK installation
        run: dotnet --version  # Check .NET version
        
      - name: Install Firefox and GeckoDriver
        run: |
          sudo apt-get update
          sudo apt-get install -y firefox
          GECKODRIVER_VERSION=$(curl -s https://api.github.com/repos/mozilla/geckodriver/releases/latest | grep 'tag_name' | cut -d\" -f4)
          wget https://github.com/mozilla/geckodriver/releases/download/$GECKODRIVER_VERSION/geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          tar -xzf geckodriver-$GECKODRIVER_VERSION-linux64.tar.gz
          sudo mv geckodriver /usr/local/bin/
      
      - name: Install xvfb
        run: sudo apt-get install -y xvfb libgtk-3-0

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build
  
      # - name: Start Xvfb and run tests
      #   env:
      #     DISPLAY: :99
      #   run: |
      #     sudo Xvfb :99 -ac &
      #     sleep 5 # Give xvfb some time to start
      #     export PATH=$PATH:/usr/local/bin
      #     dotnet test --configuration Release --no-build
