name: Selenium Tests

on:
  schedule:
    - cron: '10 12 * * *'  # Runs every day at 12:10 UTC
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0'

    - name: Install dependencies
      run: dotnet restore

    - name: Build project
      run: dotnet build --configuration Release

    - name: Run Selenium tests on Chrome
      run: |
        dotnet test --configuration Release --logger "console;verbosity=detailed" --no-build --filter "Category=InputValidation && Browser=Chrome"

    - name: Run Selenium tests on Edge
      run: |
        dotnet test --configuration Release --logger "console;verbosity=detailed" --no-build --filter "Category=InputValidation && Browser=Edge"

    - name: Run Selenium tests on Firefox
      run: |
        dotnet test --configuration Release --logger "console;verbosity=detailed" --no-build --filter "Category=InputValidation && Browser=Firefox"

    - name: Run Selenium tests on Brave
      run: |
        dotnet test --configuration Release --logger "console;verbosity=detailed" --no-build --filter "Category=InputValidation && Browser=Brave"

    - name: Run Selenium tests on Opera
      run: |
        dotnet test --configuration Release --logger "console;verbosity=detailed" --no-build --filter "Category=InputValidation && Browser=Opera"
