name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: '30 12 * * *'  # Runs at 12:30 UTC every day

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup .NET SDK
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'  # Replace with the version you are using

      - name: Install .NET SDK 6.0
        run: |
          sudo apt-get update
          sudo apt-get install -y dotnet-sdk-6.0

      - name: Verify .NET SDK installation
        run: dotnet --version  # Check .NET version

      - name: Restore dependencies
        run: dotnet restore

      - name: Build
        run: dotnet build --configuration Release

      - name: Test
        run: dotnet test --configuration Release --no-build
